// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_qrVkMg6bR70BHfZXZkZjZplYyVpuOU',
    appId: '1:842301100243:web:ed72809542d94b56410426',
    messagingSenderId: '842301100243',
    projectId: 'matchqr-2c510',
    authDomain: 'matchqr-2c510.firebaseapp.com',
    storageBucket: 'matchqr-2c510.appspot.com',
    measurementId: 'G-NLCFRXG5RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQDdQB8Ry-80_sEptozulK-dOW0ssSZU',
    appId: '1:842301100243:android:536f6f656fba5406410426',
    messagingSenderId: '842301100243',
    projectId: 'matchqr-2c510',
    storageBucket: 'matchqr-2c510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCux709Gm7IHLHS_4empmFat6H5PJnfugk',
    appId: '1:842301100243:ios:ce6755448cda3c1d410426',
    messagingSenderId: '842301100243',
    projectId: 'matchqr-2c510',
    storageBucket: 'matchqr-2c510.appspot.com',
    iosClientId:
        '842301100243-la07i9mne49bmcbpl8254dov719ralh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCux709Gm7IHLHS_4empmFat6H5PJnfugk',
    appId: '1:842301100243:ios:8317672366d118ee410426',
    messagingSenderId: '842301100243',
    projectId: 'matchqr-2c510',
    storageBucket: 'matchqr-2c510.appspot.com',
    iosClientId:
        '842301100243-g1l38j8jforqebifsljmpt9eji3i1uqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentTool.RunnerTests',
  );
}
