// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxuDMW2VV0A-tX0thVAaJe0snYukkVVzY',
    appId: '1:934823142977:web:a6d0fa121413022416c8c0',
    messagingSenderId: '934823142977',
    projectId: 'misadonate',
    authDomain: 'misadonate.firebaseapp.com',
    storageBucket: 'misadonate.appspot.com',
    measurementId: 'G-5N7VTET04T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeyAI3KdpdTFyCYEg8eoDyyMX_G1UpYA',
    appId: '1:934823142977:android:16f785c5c1231dc116c8c0',
    messagingSenderId: '934823142977',
    projectId: 'misadonate',
    storageBucket: 'misadonate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5QQ1NsH0RpFeQMSr61CIzZpxqXkjGMtw',
    appId: '1:934823142977:ios:89f2ecaba0eca96b16c8c0',
    messagingSenderId: '934823142977',
    projectId: 'misadonate',
    storageBucket: 'misadonate.appspot.com',
    iosClientId: '934823142977-emq57r1hvnncbs26u60a178j178fr4db.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5QQ1NsH0RpFeQMSr61CIzZpxqXkjGMtw',
    appId: '1:934823142977:ios:24f692df5852aef616c8c0',
    messagingSenderId: '934823142977',
    projectId: 'misadonate',
    storageBucket: 'misadonate.appspot.com',
    iosClientId: '934823142977-fj29pe7ulnm29rfjekqqqkq5glb1tv7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentTool.RunnerTests',
  );
}
